version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019 Preview
install:
  - cinst dotnetcore-sdk --version 3.0.100
  - dotnet new -i Microsoft.AspNetCore.Blazor.Templates
environment:
  NuGetOrgApiKey: 
    secure: u8JpW5kkti8pMi+ra2QcXTJPhkHCA8pkKSiiZOJbcS/vFVHNvF3W8qw1Fy2If6a7
  PUBLIC_NUGET_FEED_NAME: nuget.org
  PUBLIC_NUGET_FEED_SOURCE: https://www.nuget.org/
build_script:
- cmd: ./build.cmd
test: off
artifacts:
- path: ./artifacts/*